### ISSUE TITLE
Windows Task Scheduler source is not working when user and password are not specified

### ISSUE THREAD

**Issue by andrewsav-bt** [vitor7santos/LogicMonitor#3]
Thank you for sharing this, really appreciate your work.

https://github.com/vitor7santos/LogicMonitor/blob/af2d83f74c253567fb6d563b088c6af451de1f1e/Microsoft/Windows_TaskScheduler_RunStatus/ActiveDiscovery_Script.ps1#L63

This line does not quite work with unspecified `wmi.user` and `wmi.pass` because unlike what one would expect, the value of a missing var does not get substituted at all. so instead of an empty string, you would end up with `##wmi.user##` string literal.

I changed these lines to `if ($username -and $password -and ($username -ne '##wmi.'+'user##') -and ($password -ne '##wmi.'+'pass##')) {`

**Comment by vitor7santos** [comment]
Thank you for noticing on this, I've just updated the code!
